import axios from 'axios';
import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { InformationCard } from '../components/ui/InformationCard';
import { getDashboardOverview } from '../features/dashboard/dashboard.api';
import type { DashboardOverview } from '../features/dashboard/types';

type Preset = 'TODAY' | 'YESTERDAY' | 'LAST_7_DAYS' | 'LAST_30_DAYS' | 'CUSTOM';
const message = (error: unknown) => axios.isAxiosError<{ message: string }>(error) ? error.response?.data.message ?? 'Unable to load dashboard data' : 'Unable to load dashboard data';
const money = (value: number) => `₹${value.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const date = (value: string) => new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeZone: 'Asia/Kolkata' }).format(new Date(`${value}T12:00:00Z`));
const dateTime = (value: string) => new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
const indiaToday = () => { const parts = new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date()); const part = (type: Intl.DateTimeFormatPartTypes) => parts.find((value) => value.type === type)?.value ?? ''; return `${part('year')}-${part('month')}-${part('day')}`; };
const offsetDate = (value: string, days: number) => { const [year, month, day] = value.split('-').map(Number); const result = new Date(Date.UTC(year, month - 1, day + days)); return result.toISOString().slice(0, 10); };
const rangeFor = (preset: Exclude<Preset, 'CUSTOM'>) => { const today = indiaToday(); if (preset === 'YESTERDAY') { const yesterday = offsetDate(today, -1); return { from: yesterday, to: yesterday }; } return { from: preset === 'LAST_7_DAYS' ? offsetDate(today, -6) : preset === 'LAST_30_DAYS' ? offsetDate(today, -29) : today, to: today }; };
const Status = ({ value }: { value: string }) => <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${value === 'PAID' ? 'bg-emerald-50 text-emerald-700' : value === 'UNPAID' ? 'bg-slate-100 text-slate-600' : 'bg-amber-50 text-amber-700'}`}>{value.replace('_', ' ')}</span>;
const Empty = ({ children }: { children: string }) => <p className="rounded-lg bg-slate-50 px-4 py-8 text-center text-sm text-slate-500">{children}</p>;

const RevenueTrend = ({ items }: { items: DashboardOverview['revenueTrend'] }) => {
  if (!items.length) return <Empty>No billing activity for this period.</Empty>;
  const max = Math.max(...items.map((item) => item.revenue), 1);
  const points = items.map((item, index) => `${items.length === 1 ? 50 : (index / (items.length - 1)) * 100},${92 - (item.revenue / max) * 78}`).join(' ');
  return <><div className="h-52"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full overflow-visible"><line x1="0" y1="92" x2="100" y2="92" stroke="#e2e8f0" strokeWidth="1" /><polyline points={points} fill="none" stroke="#2563eb" strokeWidth="3" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round" />{items.map((item, index) => <circle key={item.date} cx={items.length === 1 ? 50 : (index / (items.length - 1)) * 100} cy={92 - (item.revenue / max) * 78} r="1.6" fill="#2563eb" vectorEffect="non-scaling-stroke"><title>{`${date(item.date)}: ${money(item.revenue)}`}</title></circle>)}</svg></div><div className="mt-3 flex justify-between gap-3 text-xs text-slate-500"><span>{date(items[0].date)}</span><span>{date(items[items.length - 1].date)}</span></div></>;
};

export const DashboardPage = () => {
  const [preset, setPreset] = useState<Preset>('LAST_7_DAYS');
  const initialRange = rangeFor('LAST_7_DAYS');
  const [range, setRange] = useState(initialRange);
  const [customFrom, setCustomFrom] = useState(initialRange.from);
  const [customTo, setCustomTo] = useState(initialRange.to);
  const query = useQuery({ queryKey: ['dashboard-overview', range], queryFn: () => getDashboardOverview(range.from, range.to) });
  const overview = query.data;
  const applyPreset = (value: Preset) => { setPreset(value); if (value !== 'CUSTOM') setRange(rangeFor(value)); };
  const stats = useMemo(() => overview ? [
    ['Today’s Sales', money(overview.today.revenue), `${overview.today.bills} bill${overview.today.bills === 1 ? '' : 's'} today`],
    ['Today’s Bills', String(overview.today.bills), `${money(overview.today.revenue)} total billed`],
    ['Customers Served', String(overview.today.customersServed), 'Unique clients and walk-ins'],
    ['Services Performed', String(overview.today.servicesPerformed), money(overview.today.serviceRevenue)],
    ['Product Sales', String(overview.today.productsSold), money(overview.today.productRevenue)],
    ['Low Stock', String(overview.lowStock.count), overview.lowStock.count ? 'Needs attention' : 'Inventory levels look good'],
  ] : [], [overview]);
  return <div className="space-y-6">
    <section className="flex flex-col justify-between gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm lg:flex-row lg:items-center"><div><h2 className="text-xl font-bold text-slate-900">Business Overview</h2><p className="mt-1 text-sm text-slate-500">Live performance based on invoices and inventory.</p></div><div className="flex flex-wrap gap-2">{([['TODAY', 'Today'], ['YESTERDAY', 'Yesterday'], ['LAST_7_DAYS', 'Last 7 days'], ['LAST_30_DAYS', 'Last 30 days'], ['CUSTOM', 'Custom']] as [Preset, string][]).map(([value, label]) => <button key={value} onClick={() => applyPreset(value)} className={`rounded-lg px-3 py-2 text-sm font-medium ${preset === value ? 'bg-brand-600 text-white' : 'border border-slate-300 text-slate-700 hover:bg-slate-50'}`}>{label}</button>)}</div></section>
    {preset === 'CUSTOM' && <section className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:flex-row sm:items-end"><label className="text-sm font-medium text-slate-700">From<input type="date" value={customFrom} max={customTo} onChange={(event) => setCustomFrom(event.target.value)} className="mt-1 block rounded-lg border border-slate-300 px-3 py-2" /></label><label className="text-sm font-medium text-slate-700">To<input type="date" value={customTo} min={customFrom} onChange={(event) => setCustomTo(event.target.value)} className="mt-1 block rounded-lg border border-slate-300 px-3 py-2" /></label><button onClick={() => setRange({ from: customFrom, to: customTo })} disabled={!customFrom || !customTo || customFrom > customTo} className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Apply range</button></section>}
    {query.isLoading ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <div key={index} className="h-32 animate-pulse rounded-xl bg-slate-200" />)}</div> : query.isError || !overview ? <div className="rounded-xl bg-red-50 p-5 text-sm text-red-700">{message(query.error)}</div> : <>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{stats.map(([label, value, note]) => <article key={label} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold text-slate-900">{value}</p><p className="mt-2 text-xs text-slate-500">{note}</p></article>)}</section>
      <section className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><InformationCard title={`Revenue Summary · ${date(overview.range.from)} – ${date(overview.range.to)}`}><div className="mb-5 grid gap-3 sm:grid-cols-3"><Metric label="Revenue" value={money(overview.revenueSummary.revenue)} /><Metric label="Bills" value={String(overview.revenueSummary.bills)} /><Metric label="Average Bill" value={money(overview.revenueSummary.averageBillValue)} /></div><RevenueTrend items={overview.revenueTrend} /></InformationCard><InformationCard title={`Payment Methods · ${date(overview.range.from)} – ${date(overview.range.to)}`}>{overview.paymentMethods.some((item) => item.amount) ? <div className="space-y-4">{overview.paymentMethods.map((item) => <div key={item.method}><div className="mb-1 flex justify-between text-sm"><span className="font-medium">{item.method === 'MIXED' ? 'Mixed payments' : item.method}</span><span>{money(item.amount)} · {item.percentage}%</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-brand-600" style={{ width: `${item.percentage}%` }} /></div></div>)}</div> : <Empty>No payments recorded for this period.</Empty>}</InformationCard></section>
      <section className="grid gap-6 xl:grid-cols-3"><RankedCard title="Top Services" items={overview.topServices} empty="No services billed for this period." render={(item) => <><Link to={`/services/${item.id}`} className="font-medium text-slate-800 hover:text-brand-600">{item.name}</Link><p className="mt-1 text-xs text-slate-500">{item.quantity} performed · {money(item.revenue)}</p></>} /><RankedCard title="Top Products" items={overview.topProducts} empty="No products sold for this period." render={(item) => <><Link to={`/products/${item.id}`} className="font-medium text-slate-800 hover:text-brand-600">{item.name}</Link><p className="mt-1 text-xs text-slate-500">{item.quantity} units · {money(item.revenue)}</p></>} /><RankedCard title="Employee Performance" items={overview.employeePerformance} empty="No employee services recorded for this period." render={(item) => <><Link to={`/employees/${item.id}`} className="font-medium text-slate-800 hover:text-brand-600">{item.name}</Link><p className="mt-1 text-xs text-slate-500">{item.servicesPerformed} services · {money(item.revenue)} · {item.customersServed} customers</p></>} /></section>
      <section className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><InformationCard title="Recent Invoices">{overview.recentBills.length ? <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="pb-3">Invoice</th><th className="pb-3">Customer</th><th className="pb-3">Date</th><th className="pb-3">Total</th><th className="pb-3">Status</th></tr></thead><tbody className="divide-y">{overview.recentBills.map((bill) => <tr key={bill.id}><td className="py-3"><Link to={`/billing/${bill.id}`} className="font-medium text-brand-600">{bill.invoiceNumber}</Link></td><td className="py-3">{bill.customerName}<span className="block text-xs text-slate-500">{bill.customerMobile || 'Walk-in'}</span></td><td className="py-3 whitespace-nowrap">{dateTime(bill.createdAt)}</td><td className="py-3 font-medium">{money(bill.grandTotal)}</td><td className="py-3"><Status value={bill.paymentStatus} /></td></tr>)}</tbody></table></div> : <Empty>No invoices created yet.</Empty>}<Link to="/billing" className="mt-4 inline-block text-sm font-medium text-brand-600">View all invoices</Link></InformationCard><InformationCard title={`Low Stock · ${overview.lowStock.count}`}><div className="space-y-3">{overview.lowStock.products.length ? overview.lowStock.products.map((product) => <Link key={product.id} to={`/products/${product.id}`} className="flex items-center justify-between rounded-lg bg-amber-50 px-3 py-2 text-sm hover:bg-amber-100"><span className="font-medium text-slate-800">{product.name}</span><span className="text-amber-800">{product.currentStock} / min {product.minimumStockLevel}</span></Link>) : <Empty>All active products are above their minimum stock level.</Empty>}</div><Link to="/products/low-stock" className="mt-4 inline-block text-sm font-medium text-brand-600">View low stock</Link></InformationCard></section>
      <section className="flex flex-wrap gap-3"><Link to="/billing/new" className="rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white">New Bill</Link><Link to="/clients/new" className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Add Client</Link><Link to="/services/new" className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Add Service</Link><Link to="/products/new" className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Add Product</Link><Link to="/products/low-stock" className="rounded-lg border border-amber-300 px-4 py-2.5 text-sm font-semibold text-amber-800">View Low Stock</Link></section>
    </>}
  </div>;
};

const Metric = ({ label, value }: { label: string; value: string }) => <div className="rounded-lg bg-slate-50 p-3"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-lg font-bold text-slate-900">{value}</p></div>;
const RankedCard = <T extends { id: string; name: string }>({ title, items, empty, render }: { title: string; items: T[]; empty: string; render(item: T): JSX.Element }) => <InformationCard title={title}>{items.length ? <ol className="space-y-3">{items.map((item, index) => <li key={item.id} className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-brand-50 text-xs font-bold text-brand-700">{index + 1}</span><div>{render(item)}</div></li>)}</ol> : <Empty>{empty}</Empty>}</InformationCard>;
