import axios from 'axios';
import { useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { InformationCard } from '../components/ui/InformationCard';
import { getService, getServicePerformance } from '../features/services/services.api';
const apiMessage = (error: unknown) => axios.isAxiosError<{ message: string }>(error) ? error.response?.data.message ?? 'Request failed' : 'Something went wrong';
const Detail = ({ label, value }: { label: string; value: string }) => <div><dt className="text-xs font-medium uppercase tracking-wide text-slate-400">{label}</dt><dd className="mt-1 text-sm text-slate-700">{value}</dd></div>;
const date = (value: string) => new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' }).format(new Date(value));
export const ServiceDetailsPage = () => { const { id = '' } = useParams(); const query = useQuery({ queryKey: ['service', id], queryFn: () => getService(id), enabled: Boolean(id) }); const performanceQuery = useQuery({ queryKey: ['service-performance', id], queryFn: () => getServicePerformance(id), enabled: Boolean(id) }); if (query.isLoading) return <p className="text-sm text-slate-500">Loading service details…</p>; if (query.isError || !query.data) return <div className="rounded-xl bg-red-50 p-5 text-sm text-red-700">{query.isError ? apiMessage(query.error) : 'Service not found'}</div>; const service = query.data; const performance = performanceQuery.data; const cards = [{ title: 'Times Used', value: performance ? performance.timesUsed.toLocaleString('en-IN') : '—' }, { title: 'Revenue Generated', value: performance ? `₹${performance.revenueGenerated.toLocaleString('en-IN', { minimumFractionDigits: 2 })}` : '—' }, { title: 'Employees Providing Service', value: performance ? performance.employeesProvidingService.toLocaleString('en-IN') : '—' }]; return <div className="space-y-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="text-sm font-medium text-brand-600">Service details</p><h2 className="mt-1 text-2xl font-bold text-slate-900">{service.name}</h2><p className="mt-1 text-sm text-slate-500">Service information and billing performance.</p></div><div className="flex gap-3"><Link to={`/services/${id}/edit`} className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white hover:bg-brand-700">Edit Service</Link><Link to="/services" className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-white">Back to services</Link></div></div><InformationCard title="Service Information"><dl className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Detail label="Name" value={service.name} /><Detail label="Category" value={service.category} /><Detail label="Duration" value={`${service.duration} minutes`} /><Detail label="Price" value={`₹${service.price.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`} /><Detail label="Status" value={service.isActive ? 'Active' : 'Inactive'} /><Detail label="Created Date" value={date(service.createdAt)} /><Detail label="Updated Date" value={date(service.updatedAt)} /><Detail label="Description" value={service.description || '—'} /></dl></InformationCard><div className="grid gap-6 lg:grid-cols-3">{cards.map((card) => <InformationCard key={card.title} title={card.title}><p className="text-2xl font-bold text-slate-900">{performanceQuery.isLoading ? 'Loading…' : performanceQuery.isError ? 'Unavailable' : card.value}</p></InformationCard>)}</div></div>; };
