import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { FormField } from '../../components/ui/FormField';
import { SERVICE_CATEGORIES, type Service, type ServiceCategory, type ServiceInput } from './types';

const serviceSchema = z.object({ name: z.string().trim().min(1, 'Service name is required').max(150), category: z.enum(SERVICE_CATEGORIES, { required_error: 'Category is required' }), description: z.string().max(2000, 'Description must be 2,000 characters or fewer').optional(), duration: z.string().trim().refine((value) => Number.isFinite(Number(value)) && Number(value) > 0, 'Duration must be greater than zero'), price: z.string().trim().refine((value) => Number.isFinite(Number(value)) && Number(value) > 0, 'Price must be greater than zero'), isActive: z.boolean() });
type Values = z.infer<typeof serviceSchema>;
type Props = { initialValues?: Service; submitLabel: string; isSubmitting?: boolean; serverError?: string; onSubmit(values: ServiceInput): Promise<void>; };
export const ServiceForm = ({ initialValues, submitLabel, isSubmitting, serverError, onSubmit }: Props) => {
  const { register, handleSubmit, formState: { errors } } = useForm<Values>({ resolver: zodResolver(serviceSchema), defaultValues: { name: '', category: undefined, description: '', duration: '', price: '', isActive: true, ...(initialValues ? { ...initialValues, duration: String(initialValues.duration), price: String(initialValues.price) } : {}) } });
  const submit = async (values: Values) => onSubmit({ name: values.name.trim(), category: values.category as ServiceCategory, description: values.description?.trim() || undefined, duration: Number(values.duration), price: Number(values.price), isActive: values.isActive });
  return <form onSubmit={handleSubmit(submit)} className="space-y-6 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><p className="text-sm text-slate-500"><span className="font-medium text-red-600">*</span> Required field</p><div className="grid gap-5 sm:grid-cols-2"><FormField label="Service Name *" error={errors.name?.message} required {...register('name')} /><FormField label="Category *" error={errors.category?.message}>{<select {...register('category')} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 font-normal outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"><option value="">Select category</option>{SERVICE_CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select>}</FormField><FormField label="Duration (minutes) *" error={errors.duration?.message} required type="number" min="1" step="1" inputMode="numeric" {...register('duration')} /><FormField label="Price *" error={errors.price?.message} required type="number" min="0.01" step="0.01" inputMode="decimal" {...register('price')} /></div><label className="block text-sm font-medium text-slate-700">Description (optional)<textarea rows={4} {...register('description')} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 font-normal outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100" /></label>{errors.description && <p className="-mt-4 text-xs text-red-600">{errors.description.message}</p>}<label className="flex w-fit items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" className="h-4 w-4 rounded border-slate-300 text-brand-600 focus:ring-brand-500" {...register('isActive')} /> Active service</label>{serverError && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{serverError}</p>}<div className="flex justify-end"><button disabled={isSubmitting} className="rounded-lg bg-brand-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-brand-700 disabled:opacity-60">{isSubmitting ? 'Saving…' : submitLabel}</button></div></form>;
};
